const MAX_QUOTE_WORDS = 5;
const MINIMUM_HOLD_DURATION_MS = 1_600;
const HOLD_DURATION_PER_CHARACTER_MS = 45;

export interface Quote {
  text: string;
  holdDurationMs: number;
}

function defineQuote(
  text: string,
  holdDurationMs = MINIMUM_HOLD_DURATION_MS +
    text.length * HOLD_DURATION_PER_CHARACTER_MS,
): Quote {
  const wordCount = text.trim().split(/\s+/).length;

  if (wordCount > MAX_QUOTE_WORDS) {
    throw new Error(`Quotes cannot exceed ${MAX_QUOTE_WORDS} words: "${text}"`);
  }

  return { text, holdDurationMs };
}

export const WADDLES_INTRO_QUOTE = defineQuote("Hi I'm Waddles", 2_200);

export const PROGRAMMER_QUOTES = [
  defineQuote("hello world"),
  defineQuote("works on my machine"),
  defineQuote("one more commit"),
  defineQuote("ship it"),
  defineQuote("tests are green"),
  defineQuote("it compiles"),
  defineQuote("LGTM"),
  defineQuote("cache you later"),
  defineQuote("no bugs, only features"),
  defineQuote("deploy first, debug later"),
  defineQuote("commit happens"),
  defineQuote("merge happens"),
  defineQuote("trust the compiler"),
  defineQuote("read the logs"),
  defineQuote("check the stack trace"),
  defineQuote("blame the cache"),
  defineQuote("clear the cache"),
  defineQuote("restart fixes everything"),
  defineQuote("sudo make it work"),
  defineQuote("git push and pray"),
  defineQuote("force push responsibly"),
  defineQuote("rebase before breakfast"),
  defineQuote("squash it clean"),
  defineQuote("mind the merge conflict"),
  defineQuote("branches need pruning"),
  defineQuote("main is protected"),
  defineQuote("production is sacred"),
  defineQuote("staging is haunted"),
  defineQuote("localhost never lies"),
  defineQuote("DNS strikes again"),
  defineQuote("probably DNS"),
  defineQuote("always DNS"),
  defineQuote("blame the network"),
  defineQuote("check your ports"),
  defineQuote("inspect the payload"),
  defineQuote("validate your inputs"),
  defineQuote("sanitize everything"),
  defineQuote("parse, don't guess"),
  defineQuote("types save lives"),
  defineQuote("types are documentation"),
  defineQuote("null strikes again"),
  defineQuote("undefined behavior detected"),
  defineQuote("off by one"),
  defineQuote("zero indexed forever"),
  defineQuote("loops need exits"),
  defineQuote("recursion needs faith"),
  defineQuote("stack overflow incoming"),
  defineQuote("memory leak detected"),
  defineQuote("garbage collector knows"),
  defineQuote("allocate with purpose"),
  defineQuote("release the lock"),
  defineQuote("avoid shared state"),
  defineQuote("state is complicated"),
  defineQuote("immutable feels safer"),
  defineQuote("name things carefully"),
  defineQuote("naming is debugging"),
  defineQuote("comments can lie"),
  defineQuote("code tells stories"),
  defineQuote("delete dead code"),
  defineQuote("less code, fewer bugs"),
  defineQuote("keep functions tiny"),
  defineQuote("compose, don't inherit"),
  defineQuote("abstractions have rent"),
  defineQuote("premature abstraction hurts"),
  defineQuote("optimize after measuring"),
  defineQuote("benchmark before bragging"),
  defineQuote("profile the bottleneck"),
  defineQuote("latency is a feature"),
  defineQuote("fast enough ships"),
  defineQuote("async all the things"),
  defineQuote("await your promises"),
  defineQuote("promises were made"),
  defineQuote("race condition won"),
  defineQuote("deadlock says hello"),
  defineQuote("queues bring order"),
  defineQuote("events tell stories"),
  defineQuote("streams keep flowing"),
  defineQuote("backpressure is real"),
  defineQuote("retry with jitter"),
  defineQuote("exponential backoff activated"),
  defineQuote("idempotency saves weekends"),
  defineQuote("automate the boring parts"),
  defineQuote("scripts beat checklists"),
  defineQuote("CI is watching"),
  defineQuote("build failed successfully"),
  defineQuote("red build bad"),
  defineQuote("flaky tests detected"),
  defineQuote("test the happy path"),
  defineQuote("test the sad path"),
  defineQuote("mocks have opinions"),
  defineQuote("fixtures need love"),
  defineQuote("coverage isn't confidence"),
  defineQuote("reproduce before fixing"),
  defineQuote("debug with evidence"),
  defineQuote("logs or it didn't happen"),
  defineQuote("observability earns sleep"),
  defineQuote("alerts need context"),
  defineQuote("pager says hello"),
  defineQuote("rollback is a feature"),
  defineQuote("feature flags save Fridays"),
  defineQuote("toggle with care"),
  defineQuote("deployments need seatbelts"),
  defineQuote("canary knows first"),
  defineQuote("blue meets green"),
  defineQuote("release notes matter"),
  defineQuote("version everything"),
  defineQuote("semver has entered chat"),
  defineQuote("patch now, sleep later"),
  defineQuote("dependencies need boundaries"),
  defineQuote("update with confidence"),
  defineQuote("lockfiles are sacred"),
  defineQuote("pin your versions"),
  defineQuote("dependency tree grows"),
  defineQuote("package manager roulette"),
  defineQuote("another breaking change"),
  defineQuote("API contracts matter"),
  defineQuote("backward compatibility wins"),
  defineQuote("deprecate with dignity"),
  defineQuote("document the endpoint"),
  defineQuote("status codes have meaning"),
  defineQuote("four oh four"),
  defineQuote("five hundred feelings"),
  defineQuote("request timed out"),
  defineQuote("rate limits build character"),
  defineQuote("throttle with kindness"),
  defineQuote("paginate all the things"),
  defineQuote("cursor knows the way"),
  defineQuote("schema first"),
  defineQuote("migrations need backups"),
  defineQuote("database says no"),
  defineQuote("query responsibly"),
  defineQuote("indexes crave attention"),
  defineQuote("scan less, query more"),
  defineQuote("transactions need commitment"),
  defineQuote("rollback that migration"),
  defineQuote("backup before bravery"),
  defineQuote("data has gravity"),
  defineQuote("eventually consistent vibes"),
  defineQuote("consistency costs something"),
  defineQuote("distributed systems distribute surprises"),
  defineQuote("clocks cannot be trusted"),
  defineQuote("timezones strike again"),
  defineQuote("UTC keeps the peace"),
  defineQuote("timestamps tell tales"),
  defineQuote("milliseconds matter"),
  defineQuote("entropy always wins"),
  defineQuote("random is complicated"),
  defineQuote("seed your tests"),
  defineQuote("determinism feels nice"),
  defineQuote("security is everyone's job"),
  defineQuote("secrets belong elsewhere"),
  defineQuote("rotate your keys"),
  defineQuote("encrypt all the things"),
  defineQuote("hash before storing"),
  defineQuote("permissions need limits"),
  defineQuote("least privilege wins"),
  defineQuote("authenticate then authorize"),
  defineQuote("tokens eventually expire"),
  defineQuote("cookies need boundaries"),
  defineQuote("CORS says maybe"),
  defineQuote("certificates expire Friday"),
  defineQuote("HTTPS or bust"),
  defineQuote("input remains suspicious"),
  defineQuote("escape your strings"),
  defineQuote("shell injection says hi"),
  defineQuote("review the diff"),
  defineQuote("small commits tell stories"),
  defineQuote("pull requests need context"),
  defineQuote("reviewers are human"),
  defineQuote("approve with comments"),
  defineQuote("nitpick kindly"),
  defineQuote("pairing shares context"),
  defineQuote("rubber duck approves"),
  defineQuote("ask the duck"),
  defineQuote("explain it out loud"),
  defineQuote("future you is watching"),
  defineQuote("documentation prevents archaeology"),
  defineQuote("README before rescue"),
  defineQuote("examples beat explanations"),
  defineQuote("diagram the weird parts"),
  defineQuote("TODO became permanent"),
  defineQuote("technical debt compounds"),
  defineQuote("refactor with tests"),
  defineQuote("leave code better"),
  defineQuote("simplicity scales"),
  defineQuote("boring technology works"),
  defineQuote("clever code charges interest"),
  defineQuote("explicit beats magical"),
  defineQuote("defaults shape behavior"),
  defineQuote("configuration grows wild"),
  defineQuote("environment variables vanish"),
  defineQuote("containers contain surprises"),
  defineQuote("orchestrators need orchestration"),
  defineQuote("scale after demand"),
  defineQuote("cold starts need coffee"),
  defineQuote("serverless still has servers"),
  defineQuote("clouds need debugging"),
  defineQuote("uptime is teamwork"),
  defineQuote("keep calm and code"),
  defineQuote("If you're out of luck, ask the duck."),
  defineQuote("$ Waddles time is coming"),
  defineQuote("Try the duck for good luck."),
] as const satisfies readonly Quote[];
